server:
  port: ${SERVER_PORT:8080}
#  servlet:
#    context-path: /api

spring:
  application:
    name: projetos-api
  datasource:
    #url: jdbc:postgresql://127.0.0.1:5433/fiap
    #username: postgres
    #password: postgres
    #driver-class-name: org.postgresql.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console  # Caminho para acessar o console H2 no navegador
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true



    #    dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true  # To show SQL queries in the console (optional)
    open-in-view: false  # Best practice to disable Open Session in View pattern
  devtools:
    restart:
      enabled: true
logging:
  level:
    root: INFO
    br: DEBUG
    org:
      hibernate:
        SQL: DEBUG         # Ativa o log das SQL queries
        type:
          descriptor:
            sql:
              BasicBinder: TRACE  # Mostra par√¢metros das queries
api:
  security:
    token:
      secret: ${ENV_TOKEN_SECRET:token-test}